### ISSUE TITLE
recent sqlite3 upstream update breaks older systems

### ISSUE THREAD

**Issue by nnungest** [haraka/haraka-plugin-graph#23]
Systems running older versions of python broke due to sqlite3 not being pinned here. 

Opened https://github.com/haraka/haraka-plugin-graph/pull/22 to address this.

**Comment by msimerson** [comment]
What versions of python?

**Comment by nnungest-aca** [comment]
i think this is a false flag. something updated node-gyp in the dependency chain around the same time that sqlite pushed changes causing python 2 builds to fail.

**Comment by nnungest** [comment]
First noticed this shortly after sqlite3 pushed changes. This then caused builds running python 2.7 to fail. But I may have opened this in haste, as building haraka with `npm install --omit optional` still resulted in the same fail. So I have yet to identify a smoking gun it seems. Somwhere along the dependency chain node-gyp has updated causing these legacy builds to fail. I just went ahead and updated to python 3 instead.

Very strange, and coincidental timing. Can close if needed. Thanks

**Comment by msimerson** [comment]
The Python project doesn't support python 2.7 and I'm going to follow their lead.
